// Mock job data for development/demo purposes.
// Used as fallback when the API returns no data so the UI is never blank
// during local development or demos.

import type { Job } from "./api";

// Helper: generate a past ISO timestamp relative to "now".
function ago(minutes: number): string {
  return new Date(Date.now() - minutes * 60_000).toISOString();
}

function uuid(seed: number): string {
  const hex = seed.toString(16).padStart(8, "0");
  return `${hex}-mock-4a3b-9c1d-${hex}${hex.slice(0, 4)}`;
}

function accountId(n: number): string {
  return `acc_${n.toString(16).padStart(24, "0")}`;
}

export const MOCK_JOBS: Job[] = [
  {
    id: uuid(1),
    account_id: accountId(1001),
    api_key_id: "key_prod_main",
    model_alias: "hf-video-v2-standard",
    jst: "video_generate",
    endpoint: "/v1/video/generate",
    status: "completed",
    upstream_job_id: "ups_7f3a9b2c1d4e",
    latency_ms: 42300,
    poll_count: 8,
    pre_balance_h: 12000,
    actual_credits_h: 800,
    charged_credits_h: 960,
    refunded: false,
    request_ts: ago(3),
    finished_at: ago(2),
    result_url: "https://cdn.higgsfield.com/results/v2/abc123.mp4",
  },
  {
    id: uuid(2),
    account_id: accountId(1002),
    api_key_id: "key_prod_main",
    model_alias: "hf-video-v2-fast",
    jst: "video_generate",
    endpoint: "/v1/video/generate",
    status: "in_progress",
    upstream_job_id: "ups_2e8c4d1f6a7b",
    latency_ms: undefined,
    poll_count: 3,
    pre_balance_h: 8500,
    actual_credits_h: undefined,
    charged_credits_h: undefined,
    refunded: false,
    request_ts: ago(1),
  },
  {
    id: uuid(3),
    account_id: accountId(1003),
    api_key_id: "key_staging_test",
    model_alias: "hf-image-v3-hd",
    jst: "image_generate",
    endpoint: "/v1/image/generate",
    status: "completed",
    upstream_job_id: "ups_9a1b3c5d7e2f",
    latency_ms: 8740,
    poll_count: 2,
    pre_balance_h: 5200,
    actual_credits_h: 200,
    charged_credits_h: 240,
    refunded: false,
    request_ts: ago(8),
    finished_at: ago(7),
    result_url: "https://cdn.higgsfield.com/results/img/xyz789.png",
  },
  {
    id: uuid(4),
    account_id: accountId(1001),
    api_key_id: "key_prod_main",
    model_alias: "hf-video-v2-standard",
    jst: "video_generate",
    endpoint: "/v1/video/generate",
    status: "failed",
    upstream_job_id: "ups_4b6d8f0a2c4e",
    latency_ms: 65200,
    poll_count: 12,
    pre_balance_h: 11040,
    actual_credits_h: 0,
    charged_credits_h: 0,
    refunded: true,
    request_ts: ago(15),
    finished_at: ago(14),
    error: { type: "upstream_timeout", message: "Upstream provider timed out after 60s" },
  },
  {
    id: uuid(5),
    account_id: accountId(1004),
    api_key_id: "key_partner_acme",
    group_id: "grp_acme_video",
    model_alias: "hf-video-v2-cinematic",
    jst: "video_generate",
    endpoint: "/v1/video/generate",
    status: "completed",
    upstream_job_id: "ups_c3e5f7a9b1d3",
    latency_ms: 95400,
    poll_count: 18,
    pre_balance_h: 25000,
    actual_credits_h: 1600,
    charged_credits_h: 2080,
    refunded: false,
    request_ts: ago(22),
    finished_at: ago(20),
    result_url: "https://cdn.higgsfield.com/results/v2/cin_456.mp4",
  },
  {
    id: uuid(6),
    account_id: accountId(1005),
    api_key_id: "key_prod_main",
    model_alias: "hf-image-v3-standard",
    jst: "image_generate",
    endpoint: "/v1/image/generate",
    status: "pending",
    poll_count: 0,
    pre_balance_h: 3400,
    request_ts: ago(0.5),
  },
  {
    id: uuid(7),
    account_id: accountId(1006),
    api_key_id: "key_prod_secondary",
    model_alias: "hf-video-v2-fast",
    jst: "video_generate",
    endpoint: "/v1/video/generate",
    status: "timeout",
    upstream_job_id: "ups_d4f6a8c0e2b4",
    latency_ms: 120000,
    poll_count: 24,
    pre_balance_h: 7800,
    actual_credits_h: 0,
    charged_credits_h: 0,
    refunded: true,
    request_ts: ago(45),
    finished_at: ago(43),
    error: { type: "poll_timeout", message: "Max poll attempts (24) exceeded without completion" },
  },
  {
    id: uuid(8),
    account_id: accountId(1002),
    api_key_id: "key_prod_main",
    model_alias: "hf-video-v2-standard",
    jst: "video_generate",
    endpoint: "/v1/video/generate",
    status: "completed",
    upstream_job_id: "ups_e5a7b9d1f3c5",
    latency_ms: 38900,
    poll_count: 7,
    pre_balance_h: 7700,
    actual_credits_h: 800,
    charged_credits_h: 960,
    refunded: false,
    request_ts: ago(55),
    finished_at: ago(54),
    result_url: "https://cdn.higgsfield.com/results/v2/std_789.mp4",
  },
  {
    id: uuid(9),
    account_id: accountId(1007),
    cpa_partner_id: "cpa_newapi_prod",
    model_alias: "hf-video-v2-cinematic",
    jst: "video_generate",
    endpoint: "/v1/video/generate",
    status: "refunded",
    upstream_job_id: "ups_f6b8c0d2e4a6",
    latency_ms: 72100,
    poll_count: 14,
    pre_balance_h: 19000,
    actual_credits_h: 1600,
    charged_credits_h: 0,
    refunded: true,
    request_ts: ago(90),
    finished_at: ago(88),
    error: { type: "nsfw_detected", message: "Content moderation: output flagged as NSFW" },
  },
  {
    id: uuid(10),
    account_id: accountId(1003),
    api_key_id: "key_staging_test",
    model_alias: "hf-image-v3-hd",
    jst: "image_generate",
    endpoint: "/v1/image/generate",
    status: "completed",
    upstream_job_id: "ups_a7c9d1e3f5b7",
    latency_ms: 6200,
    poll_count: 1,
    pre_balance_h: 5000,
    actual_credits_h: 200,
    charged_credits_h: 240,
    refunded: false,
    request_ts: ago(120),
    finished_at: ago(119),
    result_url: "https://cdn.higgsfield.com/results/img/hd_012.png",
  },
  {
    id: uuid(11),
    account_id: accountId(1008),
    api_key_id: "key_prod_main",
    group_id: "grp_enterprise_a",
    model_alias: "hf-video-v2-standard",
    jst: "video_generate",
    endpoint: "/v1/video/generate",
    status: "failed",
    upstream_job_id: "ups_b8d0e2f4a6c8",
    latency_ms: 4500,
    poll_count: 1,
    pre_balance_h: 900,
    actual_credits_h: 0,
    charged_credits_h: 0,
    refunded: false,
    request_ts: ago(180),
    finished_at: ago(179),
    error: { type: "insufficient_balance", message: "Account balance below model minimum (need 800, have 120)" },
  },
  {
    id: uuid(12),
    account_id: accountId(1004),
    api_key_id: "key_partner_acme",
    group_id: "grp_acme_video",
    model_alias: "nano-banana-2",
    jst: "video_app",
    endpoint: "/v2/video/apps/nano_banana_2",
    status: "completed",
    upstream_job_id: "ups_c9e1f3a5b7d9",
    latency_ms: 28600,
    poll_count: 5,
    pre_balance_h: 23400,
    actual_credits_h: 400,
    charged_credits_h: 520,
    refunded: false,
    request_ts: ago(240),
    finished_at: ago(239),
    result_url: "https://cdn.higgsfield.com/results/app/banana_345.mp4",
  },
  {
    id: uuid(13),
    account_id: accountId(1009),
    api_key_id: "key_prod_main",
    model_alias: "hf-video-v2-fast",
    jst: "video_generate",
    endpoint: "/v1/video/generate",
    status: "in_progress",
    upstream_job_id: "ups_d0f2a4b6c8e0",
    poll_count: 5,
    pre_balance_h: 6300,
    request_ts: ago(2),
  },
  {
    id: uuid(14),
    account_id: accountId(1010),
    api_key_id: "key_prod_secondary",
    model_alias: "hf-image-v3-standard",
    jst: "image_generate",
    endpoint: "/v1/image/generate",
    status: "completed",
    upstream_job_id: "ups_e1a3b5c7d9f1",
    latency_ms: 5100,
    poll_count: 1,
    pre_balance_h: 2800,
    actual_credits_h: 100,
    charged_credits_h: 120,
    refunded: false,
    request_ts: ago(300),
    finished_at: ago(299),
    result_url: "https://cdn.higgsfield.com/results/img/std_678.png",
  },
  {
    id: uuid(15),
    account_id: accountId(1006),
    api_key_id: "key_prod_main",
    model_alias: "hf-video-v2-cinematic",
    jst: "video_generate",
    endpoint: "/v1/video/generate",
    status: "completed",
    upstream_job_id: "ups_f2b4c6d8e0a2",
    latency_ms: 88200,
    poll_count: 16,
    pre_balance_h: 7800,
    actual_credits_h: 1600,
    charged_credits_h: 2080,
    refunded: false,
    request_ts: ago(360),
    finished_at: ago(358),
    result_url: "https://cdn.higgsfield.com/results/v2/cin_901.mp4",
  },
];
