-- 015_model_overrides.sql: operator-editable overrides layered on top
-- of the static model catalog (data/reference/verified-models.json).
--
-- The static catalog is regenerated by dump-verified-models.mjs from
-- SEALED / image_models / video_models and reflects Higgsfield's own
-- classification. Sometimes an operator needs to correct one of those
-- verdicts at deploy time (a starter-safe model that in practice always
-- 403s the starter pool, a fresh model that dumper didn't classify
-- yet, an alias that should be exposed under a second name to a
-- downstream new-api instance, ...). Rather than fork the static file
-- or roll a new dump, this table carries a small set of operator
-- overrides applied at ModelRegistry.Resolve() / List() time.
--
-- Semantics:
--   - alias is the higgsgo canonical alias (matches verified-models.json's
--     "alias" field). PRIMARY KEY so upsert-by-alias is a single write.
--   - Tier columns are three-state INTEGERs: NULL = "inherit spec",
--     0/1 = "explicit override". A row can override any subset of tier
--     flags without touching the rest.
--   - min_credits_hundredths is nullable — NULL means inherit spec.
--   - extra_aliases_json is a JSON array of strings, or NULL/empty when
--     no extra aliases apply. These are exposed on /v1/models under
--     "extra_aliases" so a downstream aggregator (new-api) can register
--     the model under multiple names without higgsgo running its own
--     reverse proxy. Higgsgo's internal routing / auth / metering are
--     unaffected — the extra names only ride on the /v1/models feed.
--   - note is a free-form operator memo, surfaced in the admin sheet.
--
-- No foreign key to any models table because the catalog is a static
-- JSON file, not a SQL table. Overrides for a since-deleted alias are
-- harmless: Resolve() only merges when the base spec still exists.
CREATE TABLE IF NOT EXISTS model_overrides (
  alias                  TEXT PRIMARY KEY,
  starter_locked         INTEGER,
  requires_paid          INTEGER,
  requires_ultra         INTEGER,
  requires_unlim         INTEGER,
  min_credits_hundredths INTEGER,
  extra_aliases_json     TEXT,
  note                   TEXT NOT NULL DEFAULT '',
  updated_at             TEXT NOT NULL DEFAULT (datetime('now'))
);

INSERT OR IGNORE INTO schema_versions (version, applied_at) VALUES (15, CURRENT_TIMESTAMP);
